import Head from 'next/head'
import Collection from '../components/collection'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import React, { useState} from 'react'
import Main from '../components/main'

export default function Home(props) {
  const [NFTdata, setNFTdata] = useState(props.parsedData.assets)
  const [activeID, setActiveID] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-gray-900 min-h-screen w-full'>
        <Navbar />
        {
          NFTdata.length > 0 ?
            <>
              <Main activeID={activeID} NFTdata={NFTdata} />
              <Collection NFTdata={NFTdata} setActiveID={setActiveID} />
            </>
            :
            <></>
        }
        <Footer />
      </div>
    </>
  )
}

export async function getServerSideProps(context){
  const rawData = await fetch(`https://testnets-api.opensea.io/api/v1/assets?asset_contract_address=0x1eBFB443F897A9Cf6A5D3A0C668b456aba79596D&order_direction=asc`)
  const parsedData = await rawData.json()
  return{
    props:{parsedData}
  }
}
